2022-05-28 14:44:16.938 | INFO     | __main__:add_agr:4 - Your try to Computerize 8 input  For Sum and value is (45, 86, 76, 96, 23, 20, -89, 4.5)
2022-05-28 14:44:17.320 | ERROR    | __main__:<module>:2 - An error has been caught in function '<module>', process 'MainProcess' (3240), thread 'MainThread' (6364):
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x0000014EA1CC8C90, file "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 1>
           └ <function _run_code at 0x0000014EA1FB99D0>

  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x0000014EA1CC8C90, file "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 1>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py'>

  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x0000014EA62F2DC0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x0000014EA17990A0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x0000014EA4547C10>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000014EA62FF850>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x0000014EA17990A0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x0000014EA3F14160>
    │    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000014EA62FF850>

  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000014EA3F15CA0>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000014EA3EA7940>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000014EA7ED6700>(<Future finis...880>, ...],))>)>

  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x0000014EA7ED6700>(<Future finis...880>, ...],))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x0000014EA7ED6700>(<Future finis...880>, ...],))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000014EA7ED6700>(<Future finis...880>, ...],))>)>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
    await self.process_one()
          │    └ <function Kernel.process_one at 0x0000014EA5BC31F0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x0000014EA631CAC0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
    await dispatch(*args)
          │         └ ([<zmq.sugar.frame.Frame object at 0x0000014EA6314A90>, <zmq.sugar.frame.Frame object at 0x0000014EA63129E0>, <zmq.sugar.fram...
          └ <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x0000014EA631CAC0>>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
          └ <coroutine object Kernel.execute_request at 0x0000014EA789CDC0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x0000014EA7941640>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 353, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
          │     │        │                   │                     └ False
          │     │        │                   └ True
          │     │        └ 'num=45,86,76,96,23,20,-89,4.5,789,"str"\nadd_agr(*num)'
          │     └ <function ZMQInteractiveShell.run_cell at 0x0000014EA5BED790>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
                 │                    │               │       └ {'store_history': True, 'silent': False}
                 │                    │               └ ('num=45,86,76,96,23,20,-89,4.5,789,"str"\nadd_agr(*num)',)
                 │                    └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>
                 └ <class 'ipykernel.zmqshell.ZMQInteractiveShell'>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x0000014EA48E1820>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
    return runner(coro)
           │      └ <coroutine object InteractiveShell.run_cell_async at 0x0000014EA794D540>
           └ <function _pseudo_sync_runner at 0x0000014EA48C8E50>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x0000014EA794D540>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ 'C:\\Users\\HP\\AppData\\Local\\Temp/ipykernel_3240/2226938700.py'
                       │    │             │        └ [<ast.Assign object at 0x0000014EA7EB8370>, <ast.Expr object at 0x0000014EA7EB8D60>]
                       │    │             └ <ast.Module object at 0x0000014EA7EB8E20>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x0000014EA48E1AF0>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
              │    │        │     │               └ False
              │    │        │     └ <ExecutionResult object at 14ea7eb85e0, execution_count=68 error_before_exec=None error_in_exec=None info=<ExecutionInfo obje...
              │    │        └ <code object <module> at 0x0000014EA8250190, file "C:\Users\HP\AppData\Local\Temp/ipykernel_3240/2226938700.py", line 2>
              │    └ <function InteractiveShell.run_code at 0x0000014EA48E1C10>
              └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ {'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, ...
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>
         │         │    └ <property object at 0x0000014EA48D3680>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>
         └ <code object <module> at 0x0000014EA8250190, file "C:\Users\HP\AppData\Local\Temp/ipykernel_3240/2226938700.py", line 2>

> File "C:\Users\HP\AppData\Local\Temp/ipykernel_3240/2226938700.py", line 2, in <module>
    add_agr(*num)
    │        └ (45, 86, 76, 96, 23, 20, -89, 4.5, 789, 'str')
    └ <function add_agr at 0x0000014EA78B1040>

  File "C:\Users\HP\AppData\Local\Temp/ipykernel_3240/486497072.py", line 3, in add_agr
    Sum_of_nos=sum(args)
                   └ (45, 86, 76, 96, 23, 20, -89, 4.5, 789, 'str')

TypeError: unsupported operand type(s) for +: 'float' and 'str'
2022-05-28 14:44:19.407 | ERROR    | __main__:<module>:2 - An error has been caught in function '<module>', process 'MainProcess' (3240), thread 'MainThread' (6364):
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x0000014EA1CC8C90, file "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 1>
           └ <function _run_code at 0x0000014EA1FB99D0>

  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x0000014EA1CC8C90, file "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 1>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py'>

  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x0000014EA62F2DC0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x0000014EA17990A0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x0000014EA4547C10>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000014EA62FF850>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x0000014EA17990A0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x0000014EA3F14160>
    │    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000014EA62FF850>

  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000014EA3F15CA0>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000014EA3EA7940>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000014EA7EB8100>(<Future finis...880>, ...],))>)>

  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x0000014EA7EB8100>(<Future finis...880>, ...],))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x0000014EA7EB8100>(<Future finis...880>, ...],))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000014EA7EB8100>(<Future finis...880>, ...],))>)>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
    await self.process_one()
          │    └ <function Kernel.process_one at 0x0000014EA5BC31F0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x0000014EA631CAC0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
    await dispatch(*args)
          │         └ ([<zmq.sugar.frame.Frame object at 0x0000014EA6314A90>, <zmq.sugar.frame.Frame object at 0x0000014EA63129E0>, <zmq.sugar.fram...
          └ <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x0000014EA631CAC0>>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
          └ <coroutine object Kernel.execute_request at 0x0000014EA76A0C40>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x0000014EA789CAC0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 353, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
          │     │        │                   │                     └ False
          │     │        │                   └ True
          │     │        └ 'num=45,86,76,96,23,20,-89,4.5\nadd_agr(num)'
          │     └ <function ZMQInteractiveShell.run_cell at 0x0000014EA5BED790>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
                 │                    │               │       └ {'store_history': True, 'silent': False}
                 │                    │               └ ('num=45,86,76,96,23,20,-89,4.5\nadd_agr(num)',)
                 │                    └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>
                 └ <class 'ipykernel.zmqshell.ZMQInteractiveShell'>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x0000014EA48E1820>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
    return runner(coro)
           │      └ <coroutine object InteractiveShell.run_cell_async at 0x0000014EA789CDC0>
           └ <function _pseudo_sync_runner at 0x0000014EA48C8E50>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x0000014EA789CDC0>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ 'C:\\Users\\HP\\AppData\\Local\\Temp/ipykernel_3240/2196785984.py'
                       │    │             │        └ [<ast.Assign object at 0x0000014EA7ED6790>, <ast.Expr object at 0x0000014EA7ED87F0>]
                       │    │             └ <ast.Module object at 0x0000014EA7ED6A60>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x0000014EA48E1AF0>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
              │    │        │     │               └ False
              │    │        │     └ <ExecutionResult object at 14ea7eb8a30, execution_count=69 error_before_exec=None error_in_exec=None info=<ExecutionInfo obje...
              │    │        └ <code object <module> at 0x0000014EA7A98030, file "C:\Users\HP\AppData\Local\Temp/ipykernel_3240/2196785984.py", line 2>
              │    └ <function InteractiveShell.run_code at 0x0000014EA48E1C10>
              └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ {'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, ...
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>
         │         │    └ <property object at 0x0000014EA48D3680>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000014EA6335190>
         └ <code object <module> at 0x0000014EA7A98030, file "C:\Users\HP\AppData\Local\Temp/ipykernel_3240/2196785984.py", line 2>

> File "C:\Users\HP\AppData\Local\Temp/ipykernel_3240/2196785984.py", line 2, in <module>
    add_agr(num)
    │       └ (45, 86, 76, 96, 23, 20, -89, 4.5)
    └ <function add_agr at 0x0000014EA78B1040>

  File "C:\Users\HP\AppData\Local\Temp/ipykernel_3240/486497072.py", line 3, in add_agr
    Sum_of_nos=sum(args)
                   └ ((45, 86, 76, 96, 23, 20, -89, 4.5),)

TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
2022-05-28 14:44:20.721 | INFO     | __main__:add_agr:4 - Your try to Computerize 10 input  For Sum and value is (45, 86, 76, 96, 23, 20, -89, 4.5, 789, 896)
